import React from 'react'
import styles from './TermsOfUse.module.scss'
const TermsOfUse = () => {
    return (
        <div className={styles.termsOfUse}>
            <h1>PANDORA TERMS OF USE</h1>
            <p>Your access and use of the web sites on which these terms reside (including, without limitation, versions of such websites optimized for mobile) (collectively, the "Site"), and the content and services at this Site are subject to these Terms of Use (or “Terms”), which we may update from time to time. Please read these Terms carefully before accessing or using this Site. The Site is owned or controlled by PANDORA EComm, LLC (or "Pandora"). By accessing or using this Site in any way, including, without limitation, browsing this Site, using any services, and/or submitting information to Pandora, you agree to and are bound by the terms, conditions, policies and notices contained in these Terms, including, but not limited to, conducting this transaction electronically, disclaimers of warranties, damage and remedy exclusions and limitations, binding arbitration, a jury trial waiver, and a choice of Maryland law. In arbitration, there is no judge or jury and there is less discovery and appellate review than in court.
                The terms "we," "us" and "our" refer to Pandora and any of our affiliated companies as appropriate to the context. "You" refers to any person accessing or using the Site. You and we are each referred to as “party” and are together referred to as “parties.”
                From time to time we may update this Site and these Terms. Your access and use of this Site after we post any changes to these Terms constitutes your agreement to those changes. You agree to review these Terms periodically to ensure that you are familiar with the most recent version. Pandora may, in its sole discretion, and at any time, discontinue this Site or any part thereof, with or without notice, or may prevent your use of this Site with or without notice to you. You agree that you do not have any rights in this Site and that Pandora will have no liability to you if this Site is discontinued or your ability to access the Site or any content you may have posted on the Site is terminated.</p>
            <h3>Pandora Content</h3>
            <p>Content on this Site that is provided by Pandora or its licensors, including certain graphics, photographs, images, screen shots, text, digitally downloadable files, trademarks, logos, product and program names, slogans, and the compilation of the foregoing ("Pandora Content") is the property of Pandora and its licensors, and is protected under trademark, copyright, and other intellectual property laws. Nothing contained on this Site should be construed as granting any license or right to download or use any Pandora Content.
                You agree not to download, display or use any Pandora Content located on the Site for any commercial or non-commercial purpose, in connection with products or services that are not those of Pandora, in any other manner that is likely to cause confusion among consumers, that disparages or discredits Pandora and/or its licensors, that dilutes the strength of Pandora's or its licensor's property, or that otherwise infringes Pandora's or its licensors intellectual property rights. You further agree to in no other way misuse any Pandora Content that appears on this Site.
            </p>
            <h3>Use of the Site and Posting Policy</h3>
            <p>The following requirements apply to your use of the Site: (a) you will not use any electronic communication feature of the Site for any purpose that is unlawful, tortious, abusive, intrusive on another's privacy, harassing, libelous, defamatory, embarrassing, obscene, threatening, or hateful, all as determined by Pandora in its sole and absolute discretion; (b) you will not upload, post, reproduce, or distribute any information, software, or other material protected by copyright or any other intellectual property right (as well as rights of publicity and privacy) without first obtaining the permission of the owner of such rights; (c) you will not collect or store personal data about other users; (d) you will not use the Site for any commercial purpose not expressly approved by Pandora in writing; (e) you will not upload, post, email, or otherwise transmit any advertising or promotional materials or any other form of solicitation or unauthorized communication via the Site; and (f) you will not upload, post, email, or otherwise transmit any material that contains viruses or any other computer code, files, or programs which might interrupt, limit, or interfere with the functionality of the Site or any computer software or hardware or telecommunications equipment.
                From time to time on certain areas of our Site you may be able to submit product reviews, questions, written posts/responses, images, and certain other materials ("User Content"). By using these features, you agree that you will not submit or post any content that is unlawful, harmful, tortious, defamatory, libelous, obscene, invasive of the privacy of another person, threatening, harassing, abusive, hateful, racist, infringing, pornographic, violent or otherwise objectionable or inappropriate as determined by Pandora; that you will not submit or post any content that contains personal information about any individual, violates the privacy/publicity of any other individual or entity, or includes anything that you are under a contractual obligation to keep private or confidential; that you will not impersonate any person or organization, including without limitation, the personnel of Pandora, or misrepresent an affiliation with another person or organization; and that you will not submit or post any content that contains viruses, corrupted files, or any other similar software or programs that may adversely affect the operation of the Site, or feature of the Site.
                You further understand and agree that you have no ownership rights to any account you may have with us or other access to the Site, your User Content, or other features therein. Pandora may cancel your account and delete all User Content associated with your account at any time, and without notice, if Pandora deems that you have violated these Terms, the law, or for any other reason. Pandora assumes no liability for any information removed from our Site, and reserves the right to permanently restrict access to the Site or a user account. For greater certainty, and without limiting the effect of the foregoing, Pandora reserves the right, in its sole and absolute discretion, to modify, edit or remove any User Content, or to request a user to modify or edit his or her User Content, if a complaint or notice of allegedly infringing materials is received with respect to the User Content, or for any other reason.
                By displaying, publishing, submitting or otherwise posting any User Content on or through the Site, you hereby irrevocably grant to Pandora a non-exclusive, fully sub-licensable, non-revocable, perpetual, worldwide, fully-paid, royalty free license to use, modify, publicly perform, publicly display, broadcast, publish, reproduce, and distribute such User Content in any and all media now known or hereinafter developed without the requirement to make payment to you or to any third party or the need to seek your or any third party permission. Further, you waive all moral rights in and to all User Content that you post, upload or otherwise submit to or through, the Site in favor of Pandora. This license and waiver of rights includes the right to host, index, cache, distribute, and tag any User Content, as well as the right to sublicense User Content to third parties, including other users, for use on other media or platforms known or hereinafter developed, such as for use on mobile phones, or in video, music, software or other computer programs.
                You continue to retain all ownership rights you hold in your User Content, and you retain any right to use your User Content in any way you choose, subject to these Terms and the license described herein. You represent and warrant that you own all of the User Content submitted, displayed, published or posted by you on the Site and otherwise have the right to grant the license set forth herein, and the displaying, publishing or posting of any content you submit, and our use thereof does not and will not violate the privacy rights, publicity rights, copyrights, trademark rights, patents, contract rights or any other intellectual property rights or other rights of any person or entity.
                You agree to indemnify and hold Pandora, its parents, subsidiaries, officers, employees, and website contractors and each of their officers, employees and agents harmless from any claims, damages and expenses, including reasonable attorneys' fees and costs, related to your violation of these Terms, including the above Posting Policy, or any violations thereof by your dependents or agents, or which arises from the use of any content including User Content that you submitted, posted, or otherwise provided to Pandora or this Site.

            </p>
            <h3>Intellectual Property Infringement Notification</h3>
            <p>If you are a trademark or copyright owner and you believe that your rights have been violated in any way, please complete and submit a signed copy of the form available here, and send to our designated agent: Matthew Scott, 250 West Pratt Street, 17th Floor, Baltimore, MD 21201; by fax at (443) 537-2092; or by email to USeComCopyright@pandora.net. Our agent information is provided pursuant to the Digital Millennium Copyright Act, 17 U.S.C. § 512(c)(2).</p>
            <h3>Rules for Promotions</h3>
            <p>Any sweepstakes, contests, or other promotions (collectively, “Promotions”) made available through the Site may be governed by rules that are separate from these Terms. If you participate in any Promotions, please review the applicable Official Rules as well as our Privacy Policy . If the Official Rules for a Promotion conflict with these Terms, the Promotion Official Rules will apply.</p>
            <h3>Accounts, Passwords, and Security</h3>
            <p>Certain areas of the Site require registration or otherwise ask you to provide information to participate in certain features or access certain content. If you elect not to provide such information, you may not be able to access certain content or participate in certain features of the Site.</p>
            <p>If the Site requires you to create an account or otherwise submit information, you must complete the specified process by providing us with current, complete, and accurate information as requested by the applicable registration form. It is your responsibility to maintain the currency, completeness, and accuracy of your registration data, and any loss caused by your failure to do so is your responsibility. During the registration process, you will be asked to enter your name and valid e-mail address and choose a password. It is entirely your responsibility to maintain the confidentiality of your password and account. Additionally, you are entirely responsible for any and all activities that occur under your account. You agree to notify Pandora immediately of any unauthorized use of your account. You further agree not to email, post, or otherwise disseminate any user ID, password, or other information which provides you access to the Site. Pandora is not liable for any loss that you may incur as a result of someone else using your password or account, either with or without your knowledge, and is not responsible for any delay in shutting down your account after you have reported a breach of security to us.</p>
            <h3>Use of Credit Card</h3>
            <p>If you wish to purchase any product or service made available through the Site, you may be asked to supply certain information relevant to your transaction, including without limitation your credit card number, the expiration date of your credit card, your billing address, and your shipping information. YOU REPRESENT AND WARRANT THAT YOU HAVE THE LEGAL RIGHT TO USE ANY CREDIT CARD(S) UTILIZED IN CONNECTION WITH ANY TRANSACTION. By submitting such information, you grant us or the third party collecting that information on our behalf the right to provide such information to third parties for purposes of facilitating the completion of transactions initiated by you or on your behalf. Verification of information may be required prior to the acknowledgment or completion of any transaction.</p>
            <h3>Terms of Sale</h3>
            <p>Pandora currently ships to locations within the 50 United States and Puerto Rico. At this time, Pandora is unable to ship to any other international locations outside of the United States. To learn more, visit Pandora’s Return Policy, available on the Site. Orders already in the shipping process cannot be modified. Pandora charges sales tax for merchandise ordered on the Site based on the applicable state sales tax rate of the location to which the order is being shipped. Payment conducted via the PayPal site and using PayPal services are subject to the terms and conditions set by PayPal.
                Despite our best efforts, occasional pricing and other errors may occur on the Site. Access to the Site does not constitute the right to purchase products featured. Pandora is not responsible for typographical, pricing or other errors. Products and prices of products described on the Site are subject to change at any time without notice. Pandora reserves the right to revise pricing and other errors and to cancel any order you have placed if there was an error concerning the price or availability of any item you ordered when you placed the order, even if you have received an order confirmation. If your credit card has already been charged for the purchase and your order is cancelled, Pandora will issue a credit to your credit card account in the amount of the charge. Individual bank policies will dictate when this amount is credited to your account. Pandora reserves the right to limit quantities of products purchased.
                Pandora undertakes reasonable efforts to accurately display the attributes of our products, including the applicable colors; however, the actual color you see will depend on your computer system, and we cannot guarantee that your computer will accurately display such colors.
                A valid Visa, MasterCard, Discover or American Express credit card number is required for payment. Separate charges for shipping and handling will be added to the price of the products ordered. Title to all products and risk of loss or damage will pass to the buyer upon shipment from Pandora.
                It is your responsibility to ascertain and obey all applicable local, state, federal, and international laws in regard to the possession, use, and sale of any item purchased from the Site. By placing an order, you represent that the products ordered will be used only in a lawful manner.</p>
            <h3>Representations and Limitations of Liability</h3>
            <p>To the extent permitted by the applicable law, Pandora makes no representations about the reliability of the features of this Site, the Pandora Content, User Content, or any other Site feature, and disclaims all liability in the event of any service failure. You acknowledge that any reliance on such material or systems will be at your own risk. Pandora makes no representations regarding the amount of time that any Pandora Content or User Content will be preserved.
                Pandora does not endorse, verify, evaluate or guarantee any information provided by users and nothing shall be considered as an endorsement, verification or guarantee of any User Content. You shall not create or distribute information, including but not limited to advertisements, press releases or other marketing materials, or include links to any sites which contain or suggest an endorsement by Pandora without the prior review and written approval of Pandora.
                THIS SITE IS PROVIDED ON AN "AS IS, AS AVAILABLE" BASIS. TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, NO WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THOSE OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, ARE MADE WITH RESPECT TO THIS SITE, OR ANY INFORMATION, CONTENT, MATERIALS OR PRODUCTS (INCLUDING SOFTWARE) THEREIN. UNDER NO CIRCUMSTANCES, INCLUDING NEGLIGENCE, SHALL PANDORA (INCLUDING ITS OFFICERS, DIRECTORS, EMPLOYEES, SUPPLIERS OR PROGRAMMERS) BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, PUNITIVE, OR CONSEQUENTIAL DAMAGES (COLLECTIVELY, "DAMAGES") THAT RESULT FROM THE USE OF OR INABILITY TO USE THIS SITE OR ANY PRODUCTS OR SERVICES AVAILABLE THEREON, NOR SHALL PANDORA BE RESPONSIBLE FOR ANY DAMAGES WHATSOEVER THAT RESULT FROM MISTAKES, OMISSIONS, INTERRUPTIONS, DELETION OF FILES, ERRORS, DEFECTS, DELAYS IN OPERATION OR TRANSMISSION, OR ANY FAILURE OF PERFORMANCE WHETHER OR NOT CAUSED BY EVENTS BEYOND PANDORA’S REASONABLE CONTROL, INCLUDING BUT NOT LIMITED TO ACTS OF GOD, COMMUNICATIONS LINE FAILURE, THEFT, DESTRUCTION, OR UNAUTHORIZED ACCESS TO THIS SITE'S RECORDS, PROGRAMS, OR SERVICES. UNDER NO CIRCUMSTANCES, INCLUDING BUT NOT LIMITED TO A NEGLIGENT ACT, WILL PANDORA OR ITS AFFILIATES OR AGENTS BE LIABLE FOR ANY DAMAGE OF ANY KIND THAT RESULTS FROM THE USE OF, OR THE INABILITY TO USE, THE SITE, EVEN IF PANDORA HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. YOU DOWNLOAD ALL MATERIAL AT YOUR OWN RISK. IN ADDITION, PANDORA WILL NOT BE LIABLE FOR ANY DAMAGE OF ANY KIND THAT RESULTS FROM THE USE OF, OR THE INABILITY TO USE, ANY THIRD PARTY WEBSITES AS REFERENCED BELOW, EVEN IF PANDORA HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. SOME JURISDICTIONS DO NOT ALLOW LIMITATIONS ON IMPLIED WARRANTIES OR EXCLUSION OF LIABILITY FOR CERTAIN TYPES OF DAMAGES; AS A RESULT, THE ABOVE LIMITATIONS OR EXCLUSIONS MAY NOT APPLY TO YOU IN WHOLE OR IN PART AND THE FOREGOING PARAGRAPH SHALL NOT APPLY TO A RESIDENT OF NEW JERSEY TO THE EXTENT DAMAGES TO SUCH NEW JERSEY RESIDENT ARE THE RESULT OF PANDORA'S NEGLIGENT, FRAUDULENT, OR RECKLESS ACT(S) OR INTENTIONAL MISCONDUCT.
                TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, YOU AND WE AGREE THAT NOTICE OF ANY CLAIM MUST BE PROVIDED WITHIN 180 DAYS OR IT IS OTHERWISE WAIVED AND TIME BARRED.
                ANY PRODUCTS AND/OR SERVICES DESCRIBED ON THE SITE ARE OFFERED IN JURISDICTIONS WHERE THEY MAY BE LEGALLY OFFERED FOR SALE. THE INFORMATION ON THE SITE IS NOT AN OFFER OR SOLICITATION TO ANYONE IN ANY JURISDICTION IN WHICH AN OFFER OR SOLICITATION CANNOT LEGALLY BE MADE, OR TO ANY PERSON TO WHOM IT IS UNLAWFUL TO MAKE A SOLICITATION.</p>
            <h3>Third Party Websites</h3>
            <p>This Site may hyperlink to sites not maintained by or related to Pandora. Such hyperlinks are provided as a service to users and are not sponsored by or affiliated with this Site or Pandora, and Pandora does not endorse and makes no representations or warranties about the content, completeness, or accuracy of those third party sites. Information you submit at a third party site accessible from this Site is subject to the terms of that site's privacy policy, and Pandora has no control over how your information is collected, used, or otherwise handled.</p>
            <h3>Jurisdiction</h3>
            <p>The Site is controlled and operated by Pandora from within the United States, and is not intended to subject Pandora to the laws or jurisdiction of any country other than that of the United States. We may limit the availability of the Site, in whole or in part, to any person, geographic area or jurisdiction we choose, at any time and in our sole discretion. These Terms will be governed by and construed in accordance with the laws of the state of Maryland, USA without regard to conflicts of laws principles. Unless you and Pandora agree otherwise, to the fullest extent permitted by applicable law, the state and federal courts of Howard County, Maryland will have exclusive jurisdiction over any disputes (except for disputes brought in small claims court) that are not subject to arbitration or over any action involving the applicability or enforceability of the dispute resolution provision or any of its parts. You and Pandora consent to the jurisdiction of those courts and waive any objections as to personal jurisdiction or as to the laying of venue in such courts based on inconvenient forum or any other basis or any right to seek to transfer or change venue of any such action to another court.</p>
            <h3>Class Action Waiver and Jury Trial Waiver</h3>
            <p>You and Pandora agree that, to the fullest extent permitted by applicable law, each party may bring claims (whether in court or in arbitration) against the other only in an individual capacity, and not participate as a plaintiff, claimant, or class member in any class, collective, consolidated, private attorney general, or representative proceeding. This means that you and Pandora may not bring a claim on behalf of a class or group and may not bring a claim on behalf of any other person unless doing so as a parent, guardian, or ward of a minor or in another similar capacity for an individual who cannot otherwise bring their own individual claim. This also means that you and Pandora may not participate in any class, collective, consolidated, private attorney general, or representative proceeding brought by any third party. Notwithstanding the foregoing, you or Pandora may participate in a class-wide settlement.
                To the fullest extent permitted by applicable law, you and Pandora also agree to waive any right to a trial by jury.</p>
            <h3>Miscellaneous</h3>
            <p>Both you and Pandora acknowledge and agree that no partnership is formed and neither of you nor Pandora has the power or the authority to obligate or bind the other.
                On certain areas of our Site, you may be given the ability to provide us with personally identifiable information. Please read our Privacy Policy for more information about our information collection and use practices.
                The failure of Pandora to comply with these Terms because of an act of God, war, fire, riot, terrorism, earthquake, actions of federal, state, or local governmental authorities or for any other reason beyond the reasonable control of Pandora, shall not be deemed a breach of these Terms.
                If Pandora fails to act with respect to your breach or anyone else's breach on any occasion, Pandora is not waiving its right to act with respect to future or similar breaches.
                Except as specifically provided herein, if any provision of these Terms shall be unlawful, void or for any reason unenforceable, then that provision shall be deemed severable from these Terms  and shall not affect the validity and enforceability of any remaining provisions.
                These Terms constitute a binding agreement between you and Pandora, and are accepted by you upon your access, use of the Site or your account. These Terms constitute the entire agreement between you and Pandora regarding the access or use of the Site and your account. By accessing or using the Site you represent that you are capable of entering into a binding agreement, and that you agree to be bound by these Terms.
                If you breach any provision of these Terms or our Privacy Policy, you may no longer use the Site. We may, in our sole discretion, change, suspend or terminate, temporarily or permanently, the Site or any part thereof or any of its features at any time, for any reason, without any notice or liability to you or any other entity. If these Terms or your permission to use the Site is terminated by us for any reason, the agreement formed by your acceptance of these Terms will nevertheless continue to apply and be binding upon you in respect of your prior use of the Site and anything relating to or arising from such use. If you are dissatisfied with the Site or with these Terms or Privacy Policy, then your sole and exclusive remedy is to discontinue accessing or using the Site. The Pandora Content, Representations, and Limitations of Liability, Indemnity Jurisdiction and Miscellaneous provisions in this agreement shall survive any termination of this agreement.</p>
        </div>
    )
}

export default TermsOfUse