import React from 'react'
import styles from './CookieContent.module.scss'
const CookieContent = () => {
    return (
        <div className={styles.cookieContent}>
            <div className={styles.container}>
                <p>Effective Date/Last Updated: June 14th, 2023

                    Unless otherwise expressly stated, capitalized terms in this Notice have the same meaning as defined in the  Privacy Policy.

                    For California, Colorado, Connecticut, Utah, and Virginia Residents: To exercise your right to opt-out of the sale of sharing of personal data as it relates to the use of cookies and other tracking technologies for analytics and targeted advertising and cross-context behavioral advertising, please see the “Your Privacy Rights” section of the U.S. Privacy Disclosures in our Privacy Policy or click here to adjust your cookie settings.</p>
                <h3>Scope of Notice</h3>
                <p>This Cookie Policy supplements the information contained in the Privacy Policy by explaining how we and our business partners and services providers use cookies and related technologies in the course of managing and providing our online services and our communications to you. It explains what these technologies are and why we use them, as well as your rights to control our use of them.

                    In some cases, we may use cookies and related technologies described in this Cookie Policy to collect personal data, or to collect information that becomes personal data if we combine it with other information. For more details about how we process your personal data, please review the  Privacy Policy.</p>
                <h3>What Are Cookies and Related Technologies</h3>
                <p>Cookies are small data files that are stored on your computer that allow us and our third-party partners and providers to collect certain information about your interactions with our email communications, websites and other online services.  We and our third-party partners and providers may also use other, related technologies to collect this information, such as web beacons, pixels, embedded scripts, location-identifying technologies and logging technologies (collectively, “cookies”).</p>
                <h3>What We Collect When Using Cookies</h3>
                <p>We and our third-party partners and providers may use cookies to automatically collect certain types of usage information about how you access and use the services when you visit or interact with our email communications or websites or otherwise engage with us through a computer or mobile device. For example, we may collect log data about your device and its software, such as your IP address, operating system, browser type, date/time of your visit, and other similar information. We may collect analytics data or use third-party analytics tools such as Google Analytics to help us measure usage and activity trends for our online services and better understand our customer base.

                    Third-party partners and providers may also collect personal data about your online activities over time and across different websites when you use our websites and online services.

                </p>
                <h3>Third Party Data Collection & Interest-Based Advertising</h3>
                <p>We participate in interest-based advertising and use third party advertising companies to serve you targeted advertisements based on your browsing history. We permit third party online advertising networks, social media companies and other third-party services, to collect information about your use of our online services over time so that they may play or display ads on our services, on other websites, or services you may use, and on other devices you may use. Typically, though not always, the information used for interest-based advertising is collected through tracking technologies, such as  cookies, web beacons, embedded scripts, location-identifying technologies, and similar technology (collectively, “tracking technologies”), which recognize the device you are using and collect information, including click stream information, browser type, time and date you visited the site, AdID, precise geolocation and other information. We may share a common account identifier (such as a hashed email address or user ID) with our third-party advertising partners to help identify you across devices. We and our third-party partners use this information to make the advertisements you see online more relevant to your interests, as well as to provide advertising-related services such as reporting, attribution, analytics and market research. We may also use services provided by third parties (such as social media platforms) to serve targeted ads to you and others on such platforms. We may do this by providing a hashed version of your email address or other information to the platform provider. See “ Your Choices About Online Ads ” below, to learn more about interest-based advertising.

                    Social Media Widgets and Advertising.  Our services may include social media features, such as the Facebook Like button, Pinterest, Instagram, Twitter or other widgets. These social media companies may recognize you and collect information about your visit to our services, and they may set a cookie or employ other tracking technologies. Your interactions with those features are governed by the privacy policies of those companies.

                    We display targeted advertising to you through social media platforms, such as Facebook, Twitter, Instagram, LinkedIn and other social media forums. These companies have interest-based advertising programs that allow us to direct advertisements to users who have shown interest in our services while those users are on the social media platform, or to groups of other users who share similar traits, such as likely commercial interests and demographics. We may share a unique identifier, such as a user ID or hashed email address, with these platform providers or they may collect information from our website visitors through a first-party pixel, in order to direct targeted advertising to you or to a custom audience on the social media platform. These advertisements are governed by the privacy policies of those social media companies that provide them. If you do not want to receive targeted ads on your social networks, you may be able to adjust your advertising preferences through your settings on those networks. You may learn more about advertising preferences by clicking on the links provided below. Please note that these links are provided for your convenience only and we do not control the content or features that may be available on these third party services. </p>
                <p>Facebook. To learn more about your advertising preferences on Facebook Companies, click here
                    Twitter. To learn more about privacy controls for personalized ads on Twitter, click here
                    LinkedIn. To learn more about advertising preferences on LinkedIn, click here
                    Third Party Partners.   The following is a sample of the third-party service partners we work with to provide advertising services. We will strive to update this list if or when we work with new partners which offer you choices about the collection of your information, but as partners change and new technologies become available, this list is likely to change over time and may not always reflect our current partners.
                </p>
                <h3>How We Use That Information</h3>
                <p>We use or may use the data collected through cookies to: (a) recognize new or current customers and remember information so that you will not have to re-enter it during your visit or the next time you visit our websites and online services; (b) provide and monitor the effectiveness of our websites and online services; (c) monitor online usage and activities of our websites and online services; (d) diagnose errors and problems with our websites and online services; (e) otherwise plan for and enhance our online services; (f) serve you with interest-based or targeted advertising (see below for more on interest-based advertising); and (g) facilitate the purposes identified in the Our Use of Personal Data section of our Privacy Policy.  We and our advertising partners also use the information we collect through cookies to understand your browsing activities, including across unaffiliated third-party sites, so that we can deliver ads and information about products and services that may be of interest to you.

                    Please note that we link some of the personal data we collect through cookies with the other personal data that we collect about you and for the purposes described in our Privacy Policy.</p>
                <h3>Your Choices About Cookies</h3>
                <p>If you would prefer not to accept cookies, most browsers will allow you to: (i) change your browser settings to notify you when you receive a cookie, which lets you choose whether or not to accept it; (ii) disable existing cookies; or (iii) set your browser to automatically reject cookies. Please note that doing so may negatively impact your experience using our online services, as some features and services on our online services may not work properly. In addition, if you want to reject cookies across all your browsers and devices, you will need to do so on each browser on each device you actively use. Depending on your device and operating system, you may not be able to delete or block all cookies. You may also set your email options to prevent the automatic downloading of images that may contain technologies that would allow us to know whether you have accessed our email and performed certain functions with it.

                    You can learn more about Google’s practices with Google Analytics by visiting Google’s privacy policy here. You can also view Google’s currently available opt-out options here.</p>
                <h3>Your Choices About Online Ads</h3>
                <p>Controlling Cookies and Tracking Technologies. To control your cookie preferences through our cookie management tool on the website, including to opt out of targeted advertising, please click here.

                    Most browsers also allow you to adjust your browser settings to: (i) notify you when you receive a cookie, which lets you choose whether or not to accept it; (ii) disable existing cookies; or (iii) set your browser to automatically reject cookies. Blocking or deleting cookies may negatively impact your experience using the Service, as some features and services may not work properly. Depending on your device and operating system, you may not be able to delete or block all tracking technologies.

                    You may set your e-mail options to prevent the automatic downloading of images that may contain technologies that would allow us to know whether you viewed or engaged with our emails.

                    Interest-Based Advertising.  We support the self-regulatory principles for online advertising (Principles) published by the Digital Advertising Alliance (DAA). This means that we allow you to exercise choice regarding the collection of information about your online activities over time and across third-party websites for online interest-based advertising purposes. More information about these Principles can be found at  www.aboutads.info. If you want to opt out of receiving online interest-based advertisements on your internet browser from advertisers and third parties that participate in the DAA program and perform advertising-related services for us and our partners, please follow the instructions at  www.aboutads.info/choices, or  http://www.networkadvertising.org/choices/ to place an opt-out cookie on your device indicating that you do not want to receive interest-based advertisements.  Opt-out cookies only work on the internet browser and device they are downloaded onto. If you want to opt out of interest-based advertisements across all your browsers and devices, you will need to opt out on each browser on each device you actively use. If you delete cookies on your device generally, you will need to opt out again.

                    If you want to opt out of receiving online interest-based advertisements on mobile apps, please follow the instructions at  http://www.aboutads.info/appchoices.

                    Please note that when you opt out of receiving interest-based advertisements, this does not mean you will no longer see advertisements from us or on our online services.  It means that the online ads that you do see from DAA program participants should not be based on your interests.  We are not responsible for the effectiveness of, or compliance with, any third-parties’ opt-out options or programs or the accuracy of their statements regarding their programs. In addition, third parties may still use cookies to collect information about your use of our online services, including for analytics and fraud prevention as well as any other purpose permitted under the DAA’s Principles.

                    Please note that deleting or blocking cookies may not be effective for all types of tracking technologies, such as Local Storage Objects (LSOs) like HTML5.</p>
                <h3>Updates to This Cookie Policy</h3>
                <p>We will update this Cookie Policy from time to time. When we make changes to this Cookie Policy, we will change the "Last Updated" date at the beginning of this Notice. If we make material changes to this Notice, we will notify you by email to your registered email address, by prominent posting on this website or our online services, or through other appropriate communication channels. All changes shall be effective from the date of publication unless otherwise provided in the notification.</p>
                <h3>Contact Us</h3>
                <p>If you have any questions or requests in connection with this Cookie Policy or other privacy-related matters, please send an email to  usprivacy@pandora.net.

                    Alternatively, inquiries may be addressed to:

                    Pandora Jewelry, LLC
                    250 West Pratt Street, 17th Floor
                    Baltimore, MD 21201
                    Attn: General Counsel</p>
            </div>
        </div>
    )
}

export default CookieContent